name: DevOps Pipeline

on:
  push:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t eficiencia-app .

      - name: Run container
        run: docker run -d -p 8080:8080 eficiencia-app

      - name: Wait for API
        run: |
          for i in {1..10}; do
            sleep 5
            curl -f http://localhost:8080/alertas-consumo && break
          done