name: DevOps Pipeline

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true


on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t eficiencia-app .

      - name: Run container
        run: docker run -d -p 8080:8080 eficiencia-app

      - name: Test API
        run: |
          sleep 30
          curl --fail http://localhost:8080/consumo-energia